import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from '../components/weather'
import Spinner from '../components/spinner'
import Background from '../components/background'

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_KEY}`
 

  const getWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) =>{
      setWeather(response.data);
       console.log(response.data);
    })
    setCity('')
    setLoading(false);
    
  }

  if (loading) {
return <Spinner />
  } else {
    return (
      <div>
        <Head>
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Background overlay */}
  <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/70 z-[1]" />
  <Image 
  src="https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHdlYXRoZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"
  layout="fill"
  className='object-cover'
  />
  {/* Image */}
  {/* <Background 
  weatherDescription={data.weather ? data.weather[0].main : null}
  /> */}
  {/* <div className=' flex justify-center'>
    <h1 className=' flex justify-center text-white z-10 text-5xl font-bold '> Weather App</h1>
  </div> */}
  
  <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
    <form 
    onSubmit={getWeather}
    className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
      <div>
        <input
        onChange={(e)=> setCity(e.target.value)}
        className='bg-transparent border-none text-white focus:outline-none text-2xl placeholder:text-white '
         type="text" 
         placeholder='Search City' />
      </div>
      <button 
      onClick={getWeather}>
        <BsSearch  size={25}/>
        </button>
    </form>
  </div>
  
        {weather.main && <Weather  data={weather}/>}
  
      </div>
    )

  }

}
  
